name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Set up .NET action: https://github.com/marketplace/actions/setup-net-core-sdk
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Publish app
      run: dotnet publish -c Release -o ./out
    # Azure WebApp deploy action: https://github.com/marketplace/actions/azure-webapp  
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: SampleWEBAPICICDActions
        publish-profile: ${{ secrets.AZURE_WEB_APP_SECRET }}
        package: ./out